# Generated by Django 3.2.7 on 2021-09-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_and_commentaries', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='prev_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
